server:
  port: 9090
  servlet:
    context-path: /kafka-demo

kafka:
  enable: Y
  sasl:
    path: E:/sasl/kafka_client_jaas.conf
  producer:
    servers: 192.168.29.135:9091,192.168.29.135:9092,192.168.29.135:9093
  consumer:
    servers: 192.168.29.135:9091,192.168.29.135:9092,192.168.29.135:9093
    enable:
      auto:
        commit: false
    maxPollRecordsConfig: 50
    concurrency: 1
    session:
      timeout: 150000
    auto:
      commit:
        interval: 100
      offset:
        reset: earliest
    group:
      id: kafka-track-group
  topic:
    id: test-handler-topic
  profile: dev